apiVersion: v1
kind: Pod
metadata:
  name: cuda-ubuntu2204
spec:
  restartPolicy: OnFailure
  containers:
  - name: cuda-ubuntu2204
    #image: "nvcr.io/nvidia/cuda:12.4.0-base-ubuntu22.04"
    image: "nvcr.io/nvidia/cuda:12.6.3-base-ubi9"
    resources:
      limits:
        nvidia.com/gpu: 1
    command: ["nvidia-smi"]
