apiVersion: v1
kind: Namespace
metadata:
  name: xudawen
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: xudawen
  name: xudawen
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "create", "update", "delete", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: xudawen
  namespace: xudawen
subjects:
- kind: User
  name: xudawen
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: xudawen
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: xudawen
  name: xudawen
spec:
  hard:
    nvidia.com/gpu: "40"
    #requests.cpu: "1"
    #requests.memory: "1Gi"
    #limits.cpu: "1"
    #limits.memory: "1Gi"
