apiVersion: v1  
kind: Namespace  
metadata:  
 name: yangzhongxiu  
---  
apiVersion: rbac.authorization.k8s.io/v1  
kind: Role  
metadata:  
 namespace: yangzhongxiu  
 name: yangzhongxiu  
rules:  
- apiGroups: ["*"]  
 resources: ["*"]  
 verbs: ["get", "list", "create", "update", "delete", "watch"]  
---  
apiVersion: rbac.authorization.k8s.io/v1  
kind: RoleBinding  
metadata:  
 name: yangzhongxiu  
 namespace: yangzhongxiu  
subjects:  
- kind: User  
 name: yangzhongxiu  
 apiGroup: rbac.authorization.k8s.io  
roleRef:  
 kind: Role  
 name: yangzhongxiu  
 apiGroup: rbac.authorization.k8s.io  
---  
apiVersion: v1  
kind: ResourceQuota  
metadata:  
 namespace: yangzhongxiu  
 name: yangzhongxiu  
spec:  
 hard:  
   nvidia.com/gpu: "40"
   #requests.cpu: "1"  
   #requests.memory: "1Gi"  
   #limits.cpu: "1"  
   #limits.memory: "1Gi"
